import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {Activity,Radio,Database,Globe,ShieldAlert,Play,Square,RefreshCw} from 'lucide-react'; import './style.css';
type Ev={id:string;ts:string;kind:string;title:string;message:string;[key:string]:any};
const API=import.meta.env.VITE_API_URL || 'http://localhost:8000';
const scenarios=[['bulk-success','Bulk remediation — success'],['kpi-rollback','KPI guardrail — rollback'],['a2a-scan','External A2A — RF scan'],['a2a-crash','A2A remediation — crash + reconcile'],['api-failure','MMP API failure — retry + breaker']];
function App(){const [scenario,setScenario]=useState('bulk-success'),[events,setEvents]=useState<Ev[]>([]),[running,setRunning]=useState(false),[kill,setKill]=useState(false),[runId,setRunId]=useState('');
 const start=async()=>{setEvents([]);setRunning(true);const r=await fetch(API+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario,kill_switch:kill})});const {runId}=await r.json();setRunId(runId);const es=new EventSource(API+`/api/runs/${runId}/events`);es.onmessage=e=>{const x=JSON.parse(e.data);setEvents(v=>[...v,x]);if(x.outcome||x.title==='Final outcome'){setRunning(false);es.close()}};es.onerror=()=>{setRunning(false);es.close()}};
 const current=events[events.length-1]; const counts=(k:string)=>events.filter(e=>e.kind===k).length;
 return <main><header><div className="brand"><div className="logo">A6</div><div><h1>A6 Network Operations</h1><p>Interference remediation control plane <span className="live"><i/> LIVE CONTROL PLANE</span></p></div></div><div className="headerState"><span className="dot"/> ORCHESTRATOR ONLINE <small>production · v1.0</small></div></header>
 <section className="controls"><div><label>WORKFLOW SCENARIO</label><select value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><button className="primary" onClick={start} disabled={running}><Play size={16}/>{running?'RUNNING…':'RUN WORKFLOW'}</button><button className={'kill '+(kill?'armed':'')} onClick={()=>setKill(!kill)}><ShieldAlert size={16}/> {kill?'KILL SWITCH ARMED':'KILL SWITCH'}</button><button className="icon" onClick={()=>setEvents([])}><RefreshCw size={16}/></button></section>
 <section className="hero"><div><div className="eyebrow">CURRENT EXECUTION</div><h2>{current?.title||'No active execution'}</h2><p>{current?.message||'Select a remediation policy to initiate a controlled network change.'}</p></div><div className="runmeta"><span>RUN ID</span><code>{runId||'—'}</code><span>ROUTE</span><b>{current?.route||'Event bus → Orchestrator'}</b></div></section>
 <div className="grid"><section className="panel pipeline"><div className="panelHead"><h3><Activity size={17}/> Pipeline state</h3><span className={running?'pill active':'pill'}>{running?'EXECUTING':'IDLE'}</span></div><div className="steps">{['Redis event','RF Scan Agent','Decision Agent','Remediation Agent','Final outcome'].map((s,i)=>{const hit=events.some(e=>e.title.includes(s)||e.message.includes(s));return <div className={'step '+(hit?'done':'')+(current?.title.includes(s)?' now':'')} key={s}><span>{hit?'✓':i+1}</span><b>{s}</b><small>{hit?'complete':'waiting'}</small></div>})}</div><div className="stats"><div><b>{counts('redis')}</b><small>REDIS EVENTS</small></div><div><b>{counts('api')}</b><small>API REQUESTS</small></div><div><b>{counts('sql')}</b><small>SQL OPS</small></div><div><b>{counts('reconcile')}</b><small>RECONCILIATION</small></div></div></section>
 <section className="panel activity"><div className="panelHead"><h3><Radio size={17}/> Live activity stream</h3><span className="muted">{events.length} events</span></div><div className="feed">{events.length===0?<div className="empty">Events will appear here in real time…</div>:events.slice().reverse().map(e=><article className={'event '+e.kind} key={e.id}><div className="eventIcon">{e.kind==='api'?<Globe size={14}/>:e.kind==='sql'?<Database size={14}/>:<Activity size={14}/>}</div><div className="eventBody"><div><b>{e.title}</b><time>{new Date(e.ts).toLocaleTimeString()}</time></div><p>{e.message}</p>{(e.payload||e.response)&&<details><summary>View payload / response</summary><pre>{JSON.stringify({payload:e.payload,response:e.response},null,2)}</pre></details>}</div></article>)}</div></section></div>
 <footer><span><i className="green"/> Event bus connected</span><span><i className="green"/> Supabase audit store connected</span><span><i className="green"/> Real-time telemetry active</span></footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);
